name: helpdesk

services:
  database:
    image: postgres:16.9
    container_name: helpdesk-database
    restart: unless-stopped
    ports: 
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=helpdesk
      - POSTGRES_USER=dba

volumes:
  database:
    name: helpdesk-database